name: CI

on:
  workflow_dispatch:
  push:

env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_GENERATE_ASPNET_CERTIFICATE: false

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    services:
      postgres:
        image: ankane/pgvector
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: sk-pg
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - run: dotnet restore /p:ContinuousIntegrationBuild=true
    - run: dotnet build -c Release --no-restore /p:ContinuousIntegrationBuild=true
    - run: dotnet run -c Release --project Benchmark/Benchmark.csproj
